"""add_gear_sharing_to_college_competitors

Revision ID: 109d1ac298e1
Revises: 3a1d40ce3c6a
Create Date: 2026-02-25 20:55:10.633183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109d1ac298e1'
down_revision = '3a1d40ce3c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_competitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gear_sharing', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_competitors', schema=None) as batch_op:
        batch_op.drop_column('gear_sharing')

    # ### end Alembic commands ###
