"""initial schema

Revision ID: 3a1d40ce3c6a
Revises: 
Create Date: 2026-02-23 16:39:09.707740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1d40ce3c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('college_date', sa.Date(), nullable=True),
    sa.Column('pro_date', sa.Date(), nullable=True),
    sa.Column('friday_feature_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('scoring_type', sa.String(length=20), nullable=False),
    sa.Column('scoring_order', sa.String(length=20), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_partnered', sa.Boolean(), nullable=True),
    sa.Column('partner_gender_requirement', sa.String(length=10), nullable=True),
    sa.Column('requires_dual_runs', sa.Boolean(), nullable=True),
    sa.Column('stand_type', sa.String(length=50), nullable=True),
    sa.Column('max_stands', sa.Integer(), nullable=True),
    sa.Column('has_prelims', sa.Boolean(), nullable=True),
    sa.Column('payouts', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('shirt_size', sa.String(length=10), nullable=True),
    sa.Column('is_ala_member', sa.Boolean(), nullable=True),
    sa.Column('pro_am_lottery_opt_in', sa.Boolean(), nullable=True),
    sa.Column('is_left_handed_springboard', sa.Boolean(), nullable=True),
    sa.Column('events_entered', sa.Text(), nullable=True),
    sa.Column('entry_fees', sa.Text(), nullable=True),
    sa.Column('fees_paid', sa.Text(), nullable=True),
    sa.Column('gear_sharing', sa.Text(), nullable=True),
    sa.Column('partners', sa.Text(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(length=20), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('school_abbreviation', sa.String(length=20), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_code', name='unique_team_code_per_tournament')
    )
    op.create_table('college_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('individual_points', sa.Integer(), nullable=True),
    sa.Column('events_entered', sa.Text(), nullable=True),
    sa.Column('partners', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('competitor_type', sa.String(length=20), nullable=False),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=True),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('result_unit', sa.String(length=20), nullable=True),
    sa.Column('run1_value', sa.Float(), nullable=True),
    sa.Column('run2_value', sa.Float(), nullable=True),
    sa.Column('best_run', sa.Float(), nullable=True),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('payout_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('heat_number', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('stand_assignments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heat_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('competitor_type', sa.String(length=20), nullable=False),
    sa.Column('stand_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['heat_id'], ['heats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heat_assignments')
    op.drop_table('heats')
    op.drop_table('event_results')
    op.drop_table('college_competitors')
    op.drop_table('teams')
    op.drop_table('pro_competitors')
    op.drop_table('flights')
    op.drop_table('events')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
