"""add_import_fields_to_pro_competitors

Revision ID: 41b9a6cbcfd4
Revises: 109d1ac298e1
Create Date: 2026-02-26 21:21:50.523073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b9a6cbcfd4'
down_revision = '109d1ac298e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_competitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gear_sharing_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('waiver_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('waiver_signature', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_fees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('import_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_competitors', schema=None) as batch_op:
        batch_op.drop_column('import_timestamp')
        batch_op.drop_column('total_fees')
        batch_op.drop_column('notes')
        batch_op.drop_column('waiver_signature')
        batch_op.drop_column('waiver_accepted')
        batch_op.drop_column('gear_sharing_details')
        batch_op.drop_column('submission_timestamp')

    # ### end Alembic commands ###
